### ISSUE TITLE
Actividad 1 mapa mental 

### ISSUE THREAD

**Issue by Abisaylopez** [SistemasTecTlaxiaco/actividad-1-mapa-mental-Abisaylopez#1]
[Investigación Documental .pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-mapa-mental-Abisaylopez/files/9492759/Investigacion.Documental.pdf)

Alumno: Abisay López Mendoza

**Comment by gilbertovelasco1** [comment]
14.5%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
